### ISSUE TITLE
What's the difference with Git Graph extension?

### ISSUE THREAD

**Issue by Yukaii** [vfonic/vscode-ada-lightbulb#1]
Just curious, because your extension's screenshot is actually the same with Git Graph. Is this a fork project and adding some additional features? Thank you.

- Git Graph extension: https://github.com/mhutchie/vscode-git-graph

**Comment by vfonic** [comment]
Hey @Yukaii,

Great question. This is indeed (currently) a fork of Git Graph and the UI is more-less the same (except for the git detail view that now opens at the bottom of the vs code, not inline with the commits in the graph).

I'm planning to make big changes to the extension and this was a good starting point. I think soon the extension will be quite different in the end and provide more features.

The reasons for forking, instead of only contributing to the original extension are many, but mainly: I wanted to move faster and not have to wait for PR approvals. I also wanted the freedom to modify the extension how I see it fit.
I wanted to contribute plenty of my code back to the original extension so that the original extension can still benefit, if the author decides the code is worth merging. However, we hit a rough start there. :)

You can see it in the top PR, but notice that all the other PRs are mine as well:
https://github.com/mhutchie/vscode-git-graph/pulls
Unfortunately, due to "cease and desist" I received, I decided I won't be contributing more PRs back to the original extension, but will be open for answering any questions and any help of porting functionality over, if I'm asked.

Hope that clears it up for you.

/note to self (it's on my TODO): Point back to the original extension and thank the author

**Comment by Yukaii** [comment]
Thanks for the clear explanation 👍

**Comment by vfonic** [comment]
Hey @Yukaii! I feel I can close this issue now.

I've made quite some changes to the extension today. It's still work-in-progress/beta. I hope I'll soon have it stable enough so that I'll mark it v1.0.0. Right now we're at v0.4.0. I expect it to go to about v0.10.0 with all the features I'm planning to add, and then I'll release the v1.

You can follow the changes in the [CHANGELOG](https://github.com/vfonic/vscode-ada-lightbulb/blob/master/CHANGELOG.md). I expect to bump minor version once every weekend (when I don't work on my every day job. So...about 6 weekends more and we might see v1. :)
